### PR TITLE
⬆️ Update engine and dependencies

### LINKED ISSUE #309: [bug]: NodeJS 16 actions are deprecated
### Config file of your workflow

*N/A*

### Describe the bug

When using this action, this warning will appear:

```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: srealmoreno/label-sync-action@v1.0.2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

### Expected behavior

Use NodeJS 20.

### Current behavior

Used NodeJS 16.

### Logs of the workflow

_No response_

### Aditional information

_No response_

### Self-service

- [ ] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/srealmoreno/label-sync-action/blob/main/docs/CONTRIBUTING.md).

### Are you familiar with Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/srealmoreno/label-sync-action/blob/main/docs/CODE_OF_CONDUCT.md).

### Contact Details

_No response_

### LINKED ISSUE #362: [bug]: NodeJS 16 actions are deprecated forced to use Node 20
### Config file of your workflow

_N/A_

### Describe the bug

```
The following actions uses Node.js version which is deprecated and will be forced to run on node20: srealmoreno/label-sync-action@v1.0.2. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```

### Expected behavior

Use NodeJS 20.

### Current behavior

Used NodeJS 16.

### Logs of the workflow

_No response_

### Aditional information

Related: #309 

### Self-service

- [X] I'd be willing to address this documentation request myself.

### Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/srealmoreno/label-sync-action/blob/main/docs/CONTRIBUTING.md).

### Are you familiar with Contributor Covenant Code of Conduct?

- [X] I have read the [Contributor Covenant Code of Conduct](https://github.com/srealmoreno/label-sync-action/blob/main/docs/CODE_OF_CONDUCT.md).

### Contact Details

_No response_

### PR DESCRIPTION
**Pull request by affeldt28**
# Pull request template

## Type of changes

Update all node16 to node20. Use `.nvmrc` for easier maintenance of workflows node version.

- [ ] CI
- [x] Bugfix
- [ ] Feature
- [x] Generic maintenance tasks
- [ ] Documentation content changes
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no URL changes)
- [ ] Improving performance of the project (not introducing new features)
- [ ] Other (please describe):

Resolve Issue Number: #309 #362

## What is the current behavior?

uses Node 16

## What is the new behavior?

use Node 20

### Does this introduce a breaking change?

- [x] Yes
- [ ] No

It's considered a breaking change, because of the node version change. But this doesn't affect this action.

## Other information

N/A

### CODE REVIEW

**Comment by affeldt28** [comment]
@srealmoreno could you please merge this?

**Comment by srealmoreno** [comment]
Thanks for your contribution @affeldt28 

Sorry for late, I was away for a while.

I will take an integration test and a test e2e and will merge this pr.

In addition to updating my dependencies.

For future pr please add me for reviewers.

Thanks 😃

**Review by srealmoreno — COMMENTED** [review]
Thanks for your contribution @affeldt28 

Sorry for late, I was away for a while.

I will take an integration test and a test e2e and will merge this pr.

In addition to updating my dependencies.

For future pr please add me for reviewers.

Thanks 😃

**Comment by affeldt28** [comment]
Not Stale

**Review by srealmoreno — DISMISSED** [review]

**Review by srealmoreno — DISMISSED** [review]

**Review by srealmoreno — APPROVED** [review]

**Pull request merged**
